GET  http://localhost:5000/admin
###
GET  http://localhost:5000/admin/1
###
POST   http://localhost:5000/admin
Content-Type: application/json

{
    "name": "Raju Yadera",
    "username": "admin",
    "password": "1234",
    "confPassword": "1234"
}

###
GET http://localhost:5000/admin

###
DELETE http://localhost:5000/admin/7



###
GET http://localhost:5000/siswa
###
GET http://localhost:5000/admin/1



###
POST http://localhost:5000/siswa
Content-Type: application/json

{
    "nama": "Meida Nur Afifah"
}






###
GET http://localhost:5000/absen
###
GET http://localhost:5000/absen/4
###
POST http://localhost:5000/absen
Content-Type: application/json

{
    "id_siswa": 14,
    "keterangan": "Sakit",
    "tanggal": "03/30/2023"
}